homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 53.8789067
  longitude: 11.4547403
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 17
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# Tracked history is kept for 10 days
recorder:
  purge_keep_days: 10

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
    name: Wetter

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# iOS
ios:

# eq-3 MAX!
maxcube:
  host: 192.168.1.117
  
# Embedded Mosquito MQTT broker
mqtt:
  broker: core-mosquitto
  username: homeassistant
  password: secret
  
# MQTT sensors
sensor 2:
  - platform: mqtt
    name: "WohnZi °C"
    state_topic: "/sensor/wohnzimmer/temperature"
    qos: 0
    unit_of_measurement: "ºC"
  - platform: mqtt
    name: "WohnZi %"
    state_topic: "/sensor/wohnzimmer/humidity"
    qos: 0
    unit_of_measurement: "%"

switch:
  - platform: mqtt
    name: "Relais 1"
    state_topic: "/switch/wohnzimmer/switch1"
    command_topic: "/switch/wohnzimmer/switch1/set"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: true
    qos: 0
    retain: false
  - platform: mqtt
    name: "Relais 2"
    state_topic: "/switch/wohnzimmer/switch2"
    command_topic: "/switch/wohnzimmer/switch2/set"
    availability_topic: "/switch/wohnzimmer/switch2/available"
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    qos: 0
    retain: true
    
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

